EXE=app
HAXE_BIN=haxe-bin
HAXE_LIB=Main-debug.dylib

CC=clang
CFLAGS=-Wall -g -pedantic -fsanitize=thread -fno-omit-frame-pointer -std=c99 $(HAXE_BIN)/$(HAXE_LIB) -Wl,-rpath,$(HAXE_BIN)

all: $(HAXE_BIN)/$(HAXE_LIB) $(EXE)
# tell $(EXE) where the dynamic library is located
# more information: https://stackoverflow.com/questions/27506450/clang-change-dependent-shared-library-install-name-at-link-time
	install_name_tool -change $(HAXE_LIB) @rpath/$(HAXE_LIB) $(EXE)

$(HAXE_BIN)/$(HAXE_LIB): ALWAYS_RUN
	haxe build-library.hxml

ALWAYS_RUN: ;

clean:
	rm -rf $(EXE) $(HAXE_BIN)

run: all
	./$(EXE)